language: node_js
node_js:
  - stable

script: make lint test

jobs:
  include:
    - stage: eslint
      script: make lint
    - stage: tests
      script: make test
    - stage: deploy to staging
      deploy: &heroku
        provider: heroku
        app: rende11-task-manager
        api_key: $HEROKU_AUTH_TOKEN
    - stage: test staging
      script: 'curl https://rende11-task-manager.herokuapp.com/'

