language: node_js
node_js:
  - stable


env:
  global:
    - CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: make lint test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT


jobs:
  include:
    - stage: eslint
      script: make lint
    - stage: tests
      script: make migrate && make test
    - stage: deploy to staging
      deploy: &heroku
        provider: heroku
        app: peaceful-sierra-86778
        api_key: $HEROKU_AUTH_TOKEN
    - stage: test staging
      script: 'curl https://peaceful-sierra-86778.herokuapp.com/users'




